# Generated by Django 5.2.3 on 2025-07-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_pokemon_evolve_from_pokemon_evolve_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolve_from',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='evolve_to',
        ),
    ]
